### ISSUE TITLE
Typo in code.

### ISSUE THREAD

**Issue by RaEzhov** [nn-students-2021h2/Function_explorer_bot_8#20]
In source/math/parser.py at line 161 should be f-string, but 'f' was lost. This causes the user to receive the wrong error message. Screenshot attached
![photo_2022-01-22_15-26-35](https://user-images.githubusercontent.com/79147155/150638631-e4c475a4-dcf6-45cc-be0b-feb95394fae3.jpg)

**Comment by Korostast** [comment]
Ok, I'll fix that
